#if defined __INCLUDED_AnyMAL
	#endinput
#endif

#define __INCLUDED_AnyMAL

/*
----------------
@ about
----------------

AnyMAL (Any-Mod Abstraction Layer)
Core includes.

by Shadows In Rain (aka SiR)
shadowsinrain@ya.ru

----------------
*/

// indepedent
#include <anymal_ipm>

// core
#include <anymal_auth>
#include <anymal_db>
#include <anymal_ids>
#include <anymal_mb>
#include <anymal_mm>

// advanced
#include <anymal_ids_c>
#include <anymal_sfx>

